/* Real browser, synthetic account only. Default release build, voice disabled. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { execFileSync } = require('node:child_process');
const path = require('node:path'), fs = require('node:fs'), assert = require('node:assert/strict');
assert.equal(process.env.RUN_SUPABASE_INTEGRATION, '1');
assert.equal(process.env.RUN_AI_INTEGRATION, undefined);
const root = path.resolve(__dirname, '../..');
const python = process.env.QA_PYTHON || path.join(root, process.platform === 'win32' ? 'backend/.venv/Scripts/python.exe' : 'backend/.venv/bin/python');
const config = JSON.parse(execFileSync(python, ['-c', 'import json; from dotenv import dotenv_values; print(json.dumps(dotenv_values(".env.integration")))'], { cwd: path.join(root, 'backend'), encoding: 'utf8' }));
assert.equal(config.DISPOSABLE_TEST_ACCOUNTS_CONFIRMED, '1');
const origin = 'http://127.0.0.1:5173', checks = [];
let browser, page, stage = 'launch', violations = 0, external = 0;
const pass = () => { checks.push(stage); console.log('PASS: ' + stage); };
(async () => {
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext();
  await context.addInitScript(() => {
    window.__csp = [];
    document.addEventListener('securitypolicyviolation', event => window.__csp.push(event.violatedDirective));
  });
  context.on('request', request => { if (new URL(request.url()).origin !== origin) external++; });
  page = await context.newPage();
  stage = 'real CSP and security headers with no localhost HSTS';
  const response = await page.goto(origin + '/reports');
  assert.ok(response.headers()['content-security-policy'].includes("frame-ancestors 'none'"));
  assert.ok(!response.headers()['content-security-policy'].includes('unsafe-'));
  assert.equal(response.headers()['x-frame-options'], 'DENY');
  assert.equal(response.headers()['strict-transport-security'], undefined);
  await page.getByLabel('Email address', { exact: true }).fill(config.TEST_USER_A_EMAIL);
  await page.getByLabel('Password', { exact: true }).fill(config.TEST_USER_A_PASSWORD);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('heading', { name: 'Upload a report', exact: true }).waitFor(); pass();
  stage = 'major routes have headings landmarks labels and bounded mobile layout';
  for (const route of ['/', '/reports', '/history', '/trends', '/assistant', '/settings', '/exports', '/notifications']) {
    await page.goto(origin + route);
    await page.locator('main h1').waitFor();
    await page.getByRole('button', { name: 'Sign out', exact: true }).waitFor();
    assert.equal(await page.locator('main').count(), 1);
    assert.equal(await page.locator('h1').count(), 1);
    assert.equal(await page.evaluate(() => [...document.querySelectorAll('input:not([type=hidden]),select,textarea')].filter(e => !e.labels?.length && !e.getAttribute('aria-label') && !e.getAttribute('aria-labelledby')).length), 0);
    await page.setViewportSize({ width: 375, height: 812 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    violations += await page.evaluate(() => window.__csp.length);
    await page.setViewportSize({ width: 1440, height: 1000 });
  }
  pass();
  stage = 'default release voice unavailable and no third-party requests or CSP violations';
  await page.goto(origin + '/assistant');
  await page.getByText('Voice is disabled in this release. You can type your question.', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('Enable optional voice for this visit', { exact: true }).count(), 0);
  assert.equal(external, 0); assert.equal(violations, 0); pass();
  stage = 'keyboard skip navigation reaches the main landmark';
  await page.goto(origin + '/'); await page.locator('main h1').waitFor();
  await page.locator('.skip-link').focus(); await page.keyboard.press('Enter');
  assert.ok(await page.evaluate(() => document.activeElement?.closest('main') !== null)); pass();
  stage = 'lazy chunk failure shows private recoverable boundary';
  const failure = await context.newPage();
  await failure.route('**/assets/SettingsPage-*.js', route => route.abort());
  await failure.goto(origin + '/settings');
  await failure.getByRole('heading', { name: 'This page could not be displayed.', exact: true }).waitFor();
  assert.equal(await failure.locator('.account-bar__identity').count(), 0);
  await failure.unroute('**/assets/SettingsPage-*.js');
  await failure.getByRole('button', { name: 'Reload application', exact: true }).click();
  await failure.locator('#preferred-language').waitFor(); await failure.close(); pass();
  stage = 'backend network failure shows unavailable with explicit recovery';
  const offline = await context.newPage();
  await offline.route('**/api/auth/me', route => route.abort());
  await offline.goto(origin + '/reports');
  await offline.getByText('Unable to check your session', { exact: true }).waitFor();
  assert.equal(await offline.locator('.report-row').count(), 0);
  await offline.unroute('**/api/auth/me');
  await offline.getByRole('button', { name: /try again|retry/i }).click();
  await offline.getByRole('heading', { name: 'Upload a report', exact: true }).waitFor(); await offline.close(); pass();
  stage = 'logout clears private release UI';
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.waitForURL('**/auth/sign-in'); pass();
  const output = path.join(root, '.cache/qa/phase13'); fs.mkdirSync(output, { recursive: true });
  fs.writeFileSync(path.join(output, 'release-browser.json'), JSON.stringify({ checks, violations, external }, null, 2));
})().catch(error => { console.error('FAIL: ' + stage + ' (' + error.name + ')'); process.exitCode = 1; }).finally(async () => { await browser?.close(); });
