/* Opt-in Chrome smoke test; credentials stay in ignored .env.integration. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const python = path.join(root, 'backend/.venv/Scripts/python.exe');
const config = JSON.parse(execFileSync(python, ['-c', 'import json; from dotenv import dotenv_values; print(json.dumps(dotenv_values(".env.integration")))'], { cwd: path.join(root, 'backend'), encoding: 'utf8' }));
assert.equal(config.DISPOSABLE_TEST_ACCOUNTS_CONFIRMED, '1');
const fixture = execFileSync(python, ['-c', 'import sys; from tests import extraction_fixtures as f; from tests.parameter_fixtures import NATIVE_LINES; f.LINES=NATIVE_LINES; sys.stdout.buffer.write(f.document(("native",)))'], { cwd: path.join(root, 'backend') });
const output = path.join(root, '.cache/qa/phase6');
fs.mkdirSync(output, { recursive: true });
let browser, page, stage = 'launch';
const fixtureName = 'qa-phase6-' + require('node:crypto').randomUUID() + '.pdf';
const checks = [], created = new Set(), manuals = new Set();
const passed = () => { checks.push(stage); console.log('PASS: ' + stage); };
const report = () => page.locator('.report-row').filter({ has: page.getByRole('heading', { name: fixtureName, exact: true }) });
const candidate = () => report().getByRole('article', { name: 'Candidate Hemoglobin', exact: true });
(async () => {
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  page = await context.newPage(); let errors = 0;
  page.on('pageerror', () => errors++);
  page.on('response', async response => { if (response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/reports' && response.status() === 201) created.add((await response.json()).id); });
  page.on('response', async r => { if (r.request().method() === 'POST' && new URL(r.url()).pathname === '/api/observations/manual' && r.status() === 200) manuals.add((await r.json()).id); });
  stage = 'sign in and upload real synthetic PDF';
  await page.goto('http://127.0.0.1:5173/reports');
  await page.getByLabel('Email address', { exact: true }).fill(config.TEST_USER_A_EMAIL);
  await page.getByLabel('Password', { exact: true }).fill(config.TEST_USER_A_PASSWORD);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('heading', { name: 'Upload a report', exact: true }).waitFor({ timeout: 30000 });
  await page.goto('http://127.0.0.1:5173/');
  await page.locator('.overview-counts dd').nth(2).waitFor();
  const originalCount = Number(await page.locator('.overview-counts dd').nth(2).textContent());
  await page.goto('http://127.0.0.1:5173/reports');
  await page.locator('#report-file').setInputFiles({ name: fixtureName, mimeType: 'application/pdf', buffer: fixture });
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Upload report', exact: true }).click();
  await report().getByText('Uploaded', { exact: true }).waitFor({ timeout: 30000 }); passed();
  stage = 'real text extraction and parameter extraction';
  await report().getByRole('button', { name: 'Text extraction', exact: true }).click();
  await report().getByRole('button', { name: 'Extract text', exact: true }).click();
  await report().getByRole('button', { name: 'View extracted text · Attempt 1', exact: true }).waitFor({ timeout: 45000 });
  await report().getByRole('button', { name: 'Parameter candidates', exact: true }).click();
  await report().getByRole('button', { name: 'Extract parameters', exact: true }).click();
  await candidate().waitFor({ timeout: 30000 });
  assert.equal(await report().locator('.parameter-candidate').count(), 5);
  assert.equal(await candidate().getByText('13.20', { exact: true }).count(), 1);
  assert.equal(await candidate().getByText('Needs review', { exact: true }).count(), 1); passed();
  stage = 'inspect immutable provenance and full source page';
  await candidate().getByText('Inspect source and machine result', { exact: true }).click();
  assert.equal(await candidate().locator('pre').first().textContent(), 'Hemoglobin 13.20 g/dL 12-15');
  await candidate().getByRole('button', { name: 'View source page text', exact: true }).click();
  await candidate().locator('pre').nth(1).waitFor();
  assert.ok((await candidate().locator('pre').nth(1).textContent()).includes('Vitamin D 18 ng/mL')); passed();
  stage = 'append correction, confirm review and inspect revisions';
  await candidate().getByRole('button', { name: 'Correct fields', exact: true }).click();
  await candidate().getByLabel('Value', { exact: true }).fill('13.21');
  await candidate().getByRole('button', { name: 'Save correction', exact: true }).click();
  await candidate().getByText('Corrected by you', { exact: true }).waitFor();
  assert.ok((await candidate().locator('details').textContent()).includes('13.20'));
  await candidate().getByRole('button', { name: 'Confirm reviewed', exact: true }).click();
  await candidate().getByText('Confirmed by you', { exact: true }).waitFor();
  await candidate().getByRole('button', { name: 'Review history', exact: true }).click();
  await candidate().getByRole('list', { name: 'Review revisions' }).waitFor();
  assert.equal(await candidate().getByRole('list', { name: 'Review revisions' }).locator('li').count(), 2); passed();
  stage = 'explicit publication and real dashboard';
  await candidate().getByLabel('Measurement date (optional, confirmed by you)').fill('2020-01-02');
  await candidate().getByRole('button', { name: 'Publish to health history', exact: true }).click();
  await candidate().getByRole('button', { name: 'Published to health history', exact: true }).waitFor();
  await page.goto('http://127.0.0.1:5173/');
  await page.getByText('Hemoglobin: 13.21 g/dL', { exact: true }).waitFor();
  assert.equal(await page.locator('.overview-counts dd').nth(2).textContent(), String(originalCount + 1)); passed();
  stage = 'history refresh and source evidence download';
  await page.getByRole('link', { name: 'Open health history', exact: true }).click();
  let hb = page.getByRole('article', { name: 'Observation Hemoglobin', exact: true });
  await hb.waitFor();
  await hb.getByRole('button', { name: 'Inspect provenance and revisions' }).click();
  await hb.getByRole('region', { name: 'Observation provenance' }).waitFor();
  assert.equal(await hb.locator('pre').textContent(), 'Hemoglobin 13.20 g/dL 12-15');
  assert.ok((await hb.textContent()).includes('2020-01-02'));
  const downloadEvent = page.waitForEvent('download');
  await hb.getByRole('button', { name: 'Download source report' }).click();
  assert.equal((await downloadEvent).suggestedFilename(), fixtureName);
  await page.reload(); await hb.waitFor(); passed();
  stage = 'manual entry, correction and audit';
  let form = page.getByRole('form', { name: 'Add manual measurement', exact: true });
  await form.getByLabel('Measured value (kg)', { exact: true }).fill('70.250');
  await form.getByLabel('Measurement time (UTC)', { exact: true }).fill('2020-01-01T18:45');
  await form.getByRole('button', { name: 'Save measurement', exact: true }).click();
  let weight = page.getByRole('article', { name: 'Observation Weight', exact: true });
  await weight.waitFor();
  assert.ok((await weight.textContent()).includes('Manually entered'));
  await weight.getByRole('button', { name: 'Edit measurement', exact: true }).click();
  form = weight.getByRole('form', { name: 'Edit manual measurement', exact: true });
  await form.getByLabel('Measured value (kg)', { exact: true }).fill('71.250');
  await form.getByRole('button', { name: 'Save measurement correction' }).click();
  await page.waitForFunction(() => document.querySelector('.observation-card[aria-label="Observation Weight"] .observation-value')?.textContent.includes('71.250'));
  await weight.getByRole('button', { name: 'Inspect provenance and revisions' }).click();
  await weight.getByRole('list', { name: 'Observation revisions' }).waitFor();
  assert.equal(await weight.getByRole('list', { name: 'Observation revisions' }).locator('li').count(), 2); passed();
  stage = 'desktop and mobile health-history layout';
  await page.screenshot({ path: path.join(output, 'history-desktop.png'), fullPage: true, mask: [page.locator('.account-bar__identity')] });
  await page.setViewportSize({ width: 375, height: 900 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: path.join(output, 'history-mobile.png'), fullPage: true, mask: [page.locator('.account-bar__identity')] });
  await page.setViewportSize({ width: 1440, height: 1100 }); passed();
  const inspectCandidate = async target => {
    await target.goto('http://127.0.0.1:5173/reports');
    const row = target.locator('.report-row').filter({ has: target.getByRole('heading', { name: fixtureName, exact: true }) });
    await row.getByRole('button', { name: 'Parameter candidates', exact: true }).click();
    await row.getByRole('button', { name: 'Inspect parameter attempt 1', exact: true }).click();
    return row.getByRole('article', { name: 'Candidate Hemoglobin', exact: true });
  };
  stage = 'correction invalidates history until explicit republication';
  await inspectCandidate(page);
  await candidate().getByRole('button', { name: 'Correct fields', exact: true }).click();
  await candidate().getByLabel('Value', { exact: true }).fill('13.22');
  await candidate().getByRole('button', { name: 'Save correction', exact: true }).click();
  await candidate().getByText('Corrected by you', { exact: true }).waitFor();
  await page.goto('http://127.0.0.1:5173/history');
  await weight.waitFor(); assert.equal(await hb.count(), 0);
  // Scope inactive revisions to this run's report; other owned reports may
  // retain their own superseded Hemoglobin observations.
  await page.goto('http://127.0.0.1:5173/history?report_id=' + [...created][0]);
  await page.getByLabel('Include inactive observations').check();
  await page.getByRole('button', { name: 'Apply filters' }).click();
  await hb.waitFor(); assert.ok((await hb.textContent()).includes('superseded'));
  await inspectCandidate(page);
  await candidate().getByRole('button', { name: 'Publish to health history', exact: true }).click();
  await candidate().getByRole('button', { name: 'Published to health history', exact: true }).waitFor();
  await page.goto('http://127.0.0.1:5173/history');
  await hb.waitFor(); assert.ok((await hb.textContent()).includes('13.22'));
  assert.ok((await hb.textContent()).includes('Measurement date unknown')); passed();
  stage = 'two-tab stale publication and rejection';
  const second = await context.newPage();
  stage = 'two-tab: load stale candidate';
  const stale = await inspectCandidate(second);
  stage = 'two-tab: reload first candidate';
  await inspectCandidate(page);
  stage = 'two-tab: reject current revision';
  await candidate().getByRole('button', { name: 'Reject candidate', exact: true }).click();
  await candidate().getByText('Rejected by you', { exact: true }).waitFor();
  stage = 'two-tab: stale publish conflict';
  await stale.getByRole('button', { name: 'Publish to health history', exact: true }).click();
  stage = 'two-tab: await safe error';
  await stale.getByRole('alert').waitFor();
  stage = 'two-tab: verify conflict message';
  assert.ok((await stale.getByRole('alert').textContent()).includes('changed'));
  await second.close(); passed();
  stage = 'report deletion erases derived data and preserves manual entry';
  await report().getByRole('button', { name: 'Delete report', exact: true }).click();
  await report().getByRole('button', { name: 'Confirm delete', exact: true }).click();
  stage = 'deletion: await report removal';
  await report().waitFor({ state: 'detached', timeout: 30000 });
  stage = 'deletion: unrelated manual survives';
  const removedSource = await page.evaluate(async id => {
    const response = await fetch('/api/observations?include_inactive=true&report_id=' + id);
    const body = await response.json();
    return { status: response.status, count: body.items?.length };
  }, [...created][0]);
  assert.ok(removedSource.status === 404 || (removedSource.status === 200 && removedSource.count === 0));
  await page.goto('http://127.0.0.1:5173/history?include_inactive=true');
  await weight.waitFor();
  stage = 'deletion: remove manual fixture';
  await weight.getByRole('button', { name: 'Delete measurement', exact: true }).click();
  const manualDeleted = page.waitForResponse(response => response.request().method() === 'DELETE' && new URL(response.url()).pathname.startsWith('/api/observations/'));
  await weight.getByRole('button', { name: 'Confirm delete measurement', exact: true }).click();
  stage = 'deletion: await successful manual response';
  assert.equal((await manualDeleted).status(), 200);
  stage = 'deletion: await refreshed empty history';
  await weight.waitFor({ state: 'detached' });
  if (originalCount === 0) await page.getByText('No observations match this view. Upload and review a report or add a supported measurement.', { exact: true }).waitFor();
  stage = 'deletion: overview returns to original owned state';
  await page.goto('http://127.0.0.1:5173/');
  await page.locator('.overview-counts dd').nth(2).waitFor();
  assert.equal(await page.locator('.overview-counts dd').nth(2).textContent(), String(originalCount)); passed();
  stage = 'logout and clean browser runtime';
  assert.equal(errors, 0);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.waitForURL('**/auth/sign-in'); passed();
  fs.writeFileSync(path.join(output, 'browser-results.json'), JSON.stringify({ checks, passed: checks.length }, null, 2));
})().catch(error => { console.error('FAIL: ' + stage + ' ' + error.name + (String(error.message).includes('strict mode violation') ? ' strict locator' : '') + ' (account details suppressed)'); process.exitCode = 1; }).finally(async () => {
  if (page && !page.isClosed()) await page.evaluate(async ({ reports, manuals }) => {
    const csrf = (await (await fetch('/api/auth/csrf')).json()).csrf_token;
    const headers = { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf };
    for (const id of reports) await fetch('/api/reports/' + id, { method: 'DELETE', headers, body: '{}' });
    for (const id of manuals) { const r = await fetch('/api/observations/' + id); if (r.ok) await fetch('/api/observations/' + id, { method: 'DELETE', headers, body: JSON.stringify({ expected_revision: (await r.json()).current.revision }) }); }
  }, { reports: [...created], manuals: [...manuals] }).catch(() => {});
  await browser?.close();
});
