const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const {execFileSync}=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
assert.equal(process.env.RUN_SUPABASE_INTEGRATION, '1');
assert.equal(process.env.RUN_AI_INTEGRATION, undefined);
const root=path.resolve(__dirname, '../..');
const output=path.join(root,'.cache/qa/phase4'); fs.mkdirSync(output,{recursive:true});
const config=JSON.parse(execFileSync((process.env.QA_PYTHON || path.join(root, process.platform === 'win32' ? 'backend/.venv/Scripts/python.exe' : 'backend/.venv/bin/python')),['-c','import json; from dotenv import dotenv_values; print(json.dumps(dotenv_values(".env.integration")))'],{cwd:path.join(root,'backend'),encoding:'utf8'}));
assert.equal(config.DISPOSABLE_TEST_ACCOUNTS_CONFIRMED,'1');
const fixtures=JSON.parse(execFileSync((process.env.QA_PYTHON || path.join(root, process.platform === 'win32' ? 'backend/.venv/Scripts/python.exe' : 'backend/.venv/bin/python')),['-c', 'import json,base64; from pathlib import Path; from tests.extraction_fixtures import document,image_bytes; print(json.dumps({k:base64.b64encode(v).decode() for k,v in {"multipage.pdf":document(("native","native")),"english.png":image_bytes(),"encrypted.pdf":Path("tests/fixtures/encrypted.pdf").read_bytes()}.items()}))'],{cwd:path.join(root,'backend'),encoding:'utf8'}));
let browser,page,stage='launch'; const checks=[]; const created=new Set();
const passed=()=>{checks.push(stage); console.log('PASS: '+stage)};
const row=name=>page.locator('.report-row').filter({has:page.getByRole('heading',{name,exact:true})});
async function upload(file,name,media='application/pdf'){await page.locator('#report-file').setInputFiles({name,mimeType:media,buffer:Buffer.from(fixtures[file], 'base64')});await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Upload report',exact:true}).click();await row(name).getByText('Uploaded',{exact:true}).waitFor({timeout:30000});await row(name).getByRole('button',{name:'Text extraction',exact:true}).click();await row(name).getByRole('button',{name:'Extract text',exact:true}).waitFor();}
(async()=>{
browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1100}});page=await context.newPage();let errors=0;page.on('pageerror',()=>errors++);
page.on('response',async r=>{if(r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/reports'&&r.status()===201)created.add((await r.json()).id)});
await page.goto('http://127.0.0.1:5173/reports');await page.getByLabel('Email address',{exact:true}).fill(config.TEST_USER_A_EMAIL);await page.getByLabel('Password',{exact:true}).fill(config.TEST_USER_A_PASSWORD);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Upload a report',exact:true}).waitFor({timeout:30000});
stage='native upload, process and refresh';await upload('multipage.pdf','qa-native.pdf');const accepted=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/process'));await row('qa-native.pdf').getByRole('button',{name:'Extract text',exact:true}).click();assert.equal((await accepted).status(),202);await page.reload();await row('qa-native.pdf').getByRole('button',{name:'Text extraction',exact:true}).click();await row('qa-native.pdf').getByRole('button',{name:'View extracted text · Attempt 1',exact:true}).waitFor({timeout:30000});passed();
stage='page-specific text, method and original source warning';await row('qa-native.pdf').getByRole('button',{name:'View extracted text · Attempt 1',exact:true}).click();await page.getByRole('heading',{name:'Page 2 · Native PDF text',exact:true}).waitFor();assert.ok((await page.locator('.extracted-page pre').allTextContents()).every(t=>['13.2','18','2.4','mg/dL','g/dL','ng/mL','mIU/L'].every(token=>t.includes(token))));assert.equal(await page.locator('.extracted-page').count(),2);passed();
stage='mobile extraction layout';await page.setViewportSize({width:375,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(output,'extraction-mobile.png'),fullPage:true,mask:[page.locator('.account-bar__identity')]});await page.setViewportSize({width:1440,height:1100});await page.screenshot({path:path.join(output,'extraction-desktop.png'),fullPage:true,mask:[page.locator('.account-bar__identity')]});passed();
stage='image OCR text and confidence';await upload('english.png','qa-image.png','image/png');await row('qa-image.png').getByRole('button',{name:'Extract text',exact:true}).click();await row('qa-image.png').getByRole('button',{name:'View extracted text · Attempt 1',exact:true}).waitFor({timeout:60000});await row('qa-image.png').getByRole('button',{name:'View extracted text · Attempt 1',exact:true}).click();await row('qa-image.png').getByRole('heading',{name:'Page 1 · OCR',exact:true}).waitFor();const recovered=await row('qa-image.png').locator('pre').textContent();assert.ok(['13.2','18','2.4','mg/dL','g/dL','ng/mL','mIU/L'].every(token=>recovered.includes(token)));await row('qa-image.png').getByText('Mean OCR word score:',{exact:false}).waitFor();await page.screenshot({path:path.join(output,'ocr-desktop.png'),fullPage:true,mask:[page.locator('.account-bar__identity')]});passed();stage='explicit encrypted-document failure and safe retry';await upload('encrypted.pdf','qa-encrypted.pdf');await row('qa-encrypted.pdf').getByRole('button',{name:'Extract text',exact:true}).click();await row('qa-encrypted.pdf').getByText('Password-protected PDFs are not supported.',{exact:false}).waitFor({timeout:30000});await row('qa-encrypted.pdf').getByRole('button',{name:'Retry text extraction',exact:true}).click();await row('qa-encrypted.pdf').getByText('Attempt 2 · Text extraction failed',{exact:true}).waitFor({timeout:30000});passed();
stage='deletion removes extraction view';for(const name of ['qa-native.pdf','qa-image.png','qa-encrypted.pdf']){await row(name).getByRole('button',{name:'Delete report',exact:true}).click();await row(name).getByRole('button',{name:'Confirm delete',exact:true}).click();await row(name).waitFor({state:'detached',timeout:30000})}passed();
stage='logout and clean runtime';assert.equal(errors,0);await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.waitForURL('**/auth/sign-in');passed();fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({checks,passed:checks.length},null,2));
})().catch(async error=>{if(stage==='launch'&&page)console.error('Launch state: '+new URL(page.url()).pathname+' '+JSON.stringify(await page.locator('h1').allTextContents()));let message=String(error.message).split('\n')[0];for(const value of Object.values(config)){if(value)message=message.split(value).join('[redacted]')}console.error('FAIL: '+stage+' '+error.name+' '+message.slice(0,160));process.exitCode=1}).finally(async()=>{if(page&&!page.isClosed())await page.evaluate(async ids=>{const c=await(await fetch('/api/auth/csrf')).json();for(const id of ids)await fetch('/api/reports/'+id,{method:'DELETE',headers:{'Content-Type':'application/json','X-CSRF-Token':c.csrf_token},body:'{}'})},[...created]).catch(()=>{});await browser?.close()});
