/* Phase 7 UI contract tests: real login, synthetic routed responses, zero AI calls. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const config = JSON.parse(execFileSync(path.join(root, 'backend/.venv/Scripts/python.exe'), ['-c', 'import json; from dotenv import dotenv_values; print(json.dumps(dotenv_values(".env.integration")))'], { cwd: path.join(root, 'backend'), encoding: 'utf8' }));
assert.equal(config.DISPOSABLE_TEST_ACCOUNTS_CONFIRMED, '1');
const id = '71111111-1111-4111-8111-111111111111';
const fields = { original_label: 'Hemoglobin', raw_value: '13.20', original_unit: 'g/dL', raw_reference: '12–15', canonical_metric: 'hemoglobin', numeric_value: '13.20', comparator: null, value_kind: 'numeric', source_flag: null, calculated_range_status: 'unknown' };
const fact = { evidence_id: 'e1', label: 'Hemoglobin', value: '13.20', unit: 'g/dL', reference: '12–15', source_flag: null, canonical_metric: 'hemoglobin', comparator: null, value_kind: 'numeric', page_number: 1, calculated_range_status: 'unknown' };
const item = { fact, source: { observation_id: id, candidate_id: id, source_run_id: id, parameter_run_id: id, revision: 1, review_revision: 1, page_number: 1, source_start: 0, source_end: 20, fields }, explanation: 'Hemoglobin is the oxygen-carrying protein in red blood cells.', notes: ['The application has not established whether this result is above, below or within a range.'], educational_source_url: 'https://medlineplus.gov/lab-tests/hemoglobin-test/' };
const record = { id, report_id: id, status: 'ready', provider: 'mock-test', model: 'gpt-5.6-terra', prompt_version: 'report-education-v1', schema_version: 'closed-education-v1', catalog_version: 'education-en-v1', created_at: '2026-09-18T00:00:00Z', expires_at: '2026-10-18T00:00:00Z', finished_at: '2026-09-18T00:00:01Z', error_category: null, items: [item] };
let state = { report_id: id, eligible_count: 0, evaluation_enrolled: false, provider_available: true, record: null };
let browser, page, stage = 'launch', posts = 0, reads = 0, errors = 0;
const checks = [];
const pass = () => { checks.push(stage); console.log('PASS: ' + stage); };
const output = path.join(root, '.cache/qa/phase7');
fs.mkdirSync(output, { recursive: true });
(async () => {
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  page = await browser.newPage({ viewport: { width: 1440, height: 1100 } });
  page.on('pageerror', () => errors++);
  await page.route('**/api/reports', route => route.request().method() === 'GET' ? route.fulfill({ json: { reports: [{ id, original_filename: 'synthetic-ui-contract.pdf', media_type: 'application/pdf', size_bytes: 1000, status: 'uploaded', created_at: record.created_at, updated_at: record.created_at, error_category: null }], next_cursor: null } }) : route.continue());
  await page.route(`**/api/reports/${id}/explanations`, route => {
    if (route.request().method() === 'POST') {
      posts++;
      assert.equal(route.request().postDataJSON().consent, true);
      assert.match(route.request().postDataJSON().idempotency_key, /^[0-9a-f-]{36}$/);
      state = { ...state, record: structuredClone(record) };
    } else reads++;
    return route.fulfill({ json: state });
  });
  stage = 'real login; page load does not request or generate explanations';
  await page.goto('http://127.0.0.1:5173/reports');
  await page.getByLabel('Email address', { exact: true }).fill(config.TEST_USER_A_EMAIL);
  await page.getByLabel('Password', { exact: true }).fill(config.TEST_USER_A_PASSWORD);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('heading', { name: 'synthetic-ui-contract.pdf', exact: true }).waitFor({ timeout: 30000 });
  assert.equal(posts, 0); assert.equal(reads, 0); pass();
  const region = page.getByRole('region', { name: 'Report explanation' });
  const refresh = () => region.getByRole('button', { name: 'Refresh explanation status', exact: true }).click();
  const generate = () => region.getByRole('button', { name: 'Generate educational explanation', exact: true });
  stage = 'empty and unenrolled evidence cannot generate';
  await region.getByRole('button', { name: 'Report explanation', exact: true }).click();
  await region.getByText(/0 eligible published findings/).waitFor();
  assert.equal(await generate().isDisabled(), true); assert.equal(posts, 0); pass();
  stage = 'explicit consent required for enrolled synthetic report';
  state = { ...state, eligible_count: 1, evaluation_enrolled: true };
  await refresh(); await region.getByText(/1 eligible published finding/).waitFor();
  assert.equal(await generate().isDisabled(), true);
  await region.getByRole('checkbox').check();
  assert.equal(await generate().isEnabled(), true); pass();
  stage = 'explicit generation preserves decimal, range, provenance and mock label';
  await generate().click();
  await region.getByText(/Deterministic test result/).waitFor();
  assert.equal(posts, 1);
  assert.equal(await region.locator('strong').textContent(), '13.20');
  assert.ok((await region.textContent()).includes('12–15'));
  assert.ok((await region.textContent()).includes('review 1, observation revision 1'));
  assert.equal(await region.getByRole('link', { name: /MedlinePlus/ }).getAttribute('href'), item.educational_source_url); pass();
  stage = 'refresh reuses saved result without generation';
  await refresh(); await region.getByText(/Deterministic test result/).waitFor();
  assert.equal(posts, 1); pass();
  stage = 'mobile layout and escaped untrusted report text';
  const malicious = '<img src=x onerror=alert(1)>';
  state.record = { ...record, items: [{ ...item, fact: { ...fact, label: malicious }, source: { ...item.source, fields: { ...fields, original_label: malicious } } }] };
  await refresh(); await region.getByRole('heading', { name: malicious }).waitFor();
  assert.equal(await region.locator('img').count(), 0);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await region.screenshot({ path: path.join(output, 'explanation-mobile.png') }); pass();
  stage = 'source change event clears stale content and consent';
  state.record = { ...record, status: 'stale', error_category: 'source_changed', items: [] };
  state.eligible_count = 0; state.evaluation_enrolled = false;
  await page.evaluate(id => window.dispatchEvent(new CustomEvent('swasthyalens-report-changed', { detail: id })), id);
  await region.getByText(/Source findings changed/).waitFor();
  assert.equal(await region.locator('strong').count(), 0);
  assert.equal(await region.getByRole('checkbox').isChecked(), false); pass();
  stage = 'unsupported numeric output fails closed';
  state = { ...state, eligible_count: 1, evaluation_enrolled: true, record: { ...record, items: [{ ...item, fact: { ...fact, value: '132' } }] } };
  await refresh(); await region.getByRole('alert').waitFor();
  assert.equal(await region.locator('strong').count(), 0); pass();
  stage = 'in-progress and failed states never automatically retry';
  state.record = { ...record, status: 'generating', finished_at: null, items: [] };
  await refresh(); await region.getByText(/A request is still in progress/).waitFor();
  assert.equal(await generate().isDisabled(), true); assert.equal(posts, 1);
  state.record = { ...record, status: 'failed', error_category: 'timeout', items: [] };
  await refresh(); await region.getByText(/No verified explanation was saved/).waitFor();
  assert.equal(posts, 1); pass();
  stage = 'clean browser runtime and sign out';
  assert.equal(errors, 0);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.waitForURL('**/auth/sign-in'); pass();
  fs.writeFileSync(path.join(output, 'browser-results.json'), JSON.stringify({ checks, passed: checks.length, ai_calls: 0, response_mode: 'synthetic routed contracts; real authentication' }, null, 2));
})().catch(() => { console.error('FAIL: ' + stage + ' (credentials suppressed)'); process.exitCode = 1; }).finally(async () => { await browser?.close(); });
