/* Opt-in Chrome smoke test; credentials stay in ignored .env.integration. */
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { execFileSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const python = path.join(root, 'backend/.venv/Scripts/python.exe');
const config = JSON.parse(execFileSync(python, ['-c', 'import json; from dotenv import dotenv_values; print(json.dumps(dotenv_values(".env.integration")))'], { cwd: path.join(root, 'backend'), encoding: 'utf8' }));
assert.equal(config.DISPOSABLE_TEST_ACCOUNTS_CONFIRMED, '1');
const fixture = execFileSync(python, ['-c', 'import sys; from tests import extraction_fixtures as f; from tests.parameter_fixtures import NATIVE_LINES; f.LINES=NATIVE_LINES; sys.stdout.buffer.write(f.document(("native",)))'], { cwd: path.join(root, 'backend') });
const output = path.join(root, '.cache/qa/phase5');
fs.mkdirSync(output, { recursive: true });
let browser, page, stage = 'launch';
const checks = [], created = new Set();
const passed = () => { checks.push(stage); console.log('PASS: ' + stage); };
const report = () => page.locator('.report-row').filter({ has: page.getByRole('heading', { name: 'qa-parameters.pdf', exact: true }) });
const candidate = () => report().getByRole('article', { name: 'Candidate Hemoglobin', exact: true });
(async () => {
  browser = await chromium.launch({ channel: 'chrome', headless: true });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 } });
  page = await context.newPage(); let errors = 0;
  page.on('pageerror', () => errors++);
  page.on('response', async response => { if (response.request().method() === 'POST' && new URL(response.url()).pathname === '/api/reports' && response.status() === 201) created.add((await response.json()).id); });
  stage = 'sign in and upload real synthetic PDF';
  await page.goto('http://127.0.0.1:5173/reports');
  await page.getByLabel('Email address', { exact: true }).fill(config.TEST_USER_A_EMAIL);
  await page.getByLabel('Password', { exact: true }).fill(config.TEST_USER_A_PASSWORD);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.getByRole('heading', { name: 'Upload a report', exact: true }).waitFor({ timeout: 30000 });
  await page.locator('#report-file').setInputFiles({ name: 'qa-parameters.pdf', mimeType: 'application/pdf', buffer: fixture });
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Upload report', exact: true }).click();
  await report().getByText('Uploaded', { exact: true }).waitFor({ timeout: 30000 }); passed();
  stage = 'real text extraction and parameter extraction';
  await report().getByRole('button', { name: 'Text extraction', exact: true }).click();
  await report().getByRole('button', { name: 'Extract text', exact: true }).click();
  await report().getByRole('button', { name: 'View extracted text · Attempt 1', exact: true }).waitFor({ timeout: 45000 });
  await report().getByRole('button', { name: 'Parameter candidates', exact: true }).click();
  await report().getByRole('button', { name: 'Extract parameters', exact: true }).click();
  await candidate().waitFor({ timeout: 30000 });
  assert.equal(await report().locator('.parameter-candidate').count(), 5);
  assert.equal(await candidate().getByText('13.20', { exact: true }).count(), 1);
  assert.equal(await candidate().getByText('Needs review', { exact: true }).count(), 1); passed();
  stage = 'inspect immutable provenance and full source page';
  await candidate().getByText('Inspect source and machine result', { exact: true }).click();
  assert.equal(await candidate().locator('pre').first().textContent(), 'Hemoglobin 13.20 g/dL 12-15');
  await candidate().getByRole('button', { name: 'View source page text', exact: true }).click();
  await candidate().locator('pre').nth(1).waitFor();
  assert.ok((await candidate().locator('pre').nth(1).textContent()).includes('Vitamin D 18 ng/mL')); passed();
  stage = 'append correction, confirm review and inspect revisions';
  await candidate().getByRole('button', { name: 'Correct fields', exact: true }).click();
  await candidate().getByLabel('Value', { exact: true }).fill('13.21');
  await candidate().getByRole('button', { name: 'Save correction', exact: true }).click();
  await candidate().getByText('Corrected by you', { exact: true }).waitFor();
  assert.ok((await candidate().locator('details').textContent()).includes('13.20'));
  await candidate().getByRole('button', { name: 'Confirm reviewed', exact: true }).click();
  await candidate().getByText('Confirmed by you', { exact: true }).waitFor();
  await candidate().getByRole('button', { name: 'Review history', exact: true }).click();
  await candidate().getByRole('list', { name: 'Review revisions' }).waitFor();
  assert.equal(await candidate().getByRole('list', { name: 'Review revisions' }).locator('li').count(), 2); passed();
  stage = 'desktop and mobile layouts';
  await page.screenshot({ path: path.join(output, 'parameters-desktop.png'), fullPage: true, mask: [page.locator('.account-bar__identity')] });
  await page.setViewportSize({ width: 375, height: 900 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: path.join(output, 'parameters-mobile.png'), fullPage: true, mask: [page.locator('.account-bar__identity')] }); passed();
  stage = 'refresh retains correction and machine evidence';
  await page.reload();
  await report().getByRole('button', { name: 'Parameter candidates', exact: true }).click();
  await report().getByRole('button', { name: 'Inspect parameter attempt 1', exact: true }).click();
  await candidate().getByText('Confirmed by you', { exact: true }).waitFor();
  assert.equal(await candidate().getByText('13.21', { exact: true }).count(), 1);
  await candidate().getByText('Inspect source and machine result', { exact: true }).click();
  assert.equal(await candidate().locator('pre').first().textContent(), 'Hemoglobin 13.20 g/dL 12-15'); passed();
  stage = 'reject and delete removes visible candidates';
  await candidate().getByRole('button', { name: 'Reject candidate', exact: true }).click();
  await candidate().getByText('Rejected by you', { exact: true }).waitFor();
  await report().getByRole('button', { name: 'Delete report', exact: true }).click();
  await report().getByRole('button', { name: 'Confirm delete', exact: true }).click();
  await report().waitFor({ state: 'detached', timeout: 30000 }); passed();
  stage = 'logout and clean browser runtime';
  assert.equal(errors, 0);
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.waitForURL('**/auth/sign-in'); passed();
  fs.writeFileSync(path.join(output, 'browser-results.json'), JSON.stringify({ checks, passed: checks.length }, null, 2));
})().catch(() => { console.error('FAIL: ' + stage + ' (account details suppressed)'); process.exitCode = 1; }).finally(async () => {
  if (page && !page.isClosed()) await page.evaluate(async ids => { const response = await fetch('/api/auth/csrf'); const csrf = (await response.json()).csrf_token; for (const id of ids) await fetch('/api/reports/' + id, { method: 'DELETE', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf }, body: '{}' }); }, [...created]).catch(() => {});
  await browser?.close();
});
