import { accountMutation, accountOwnedRead } from './auth'
import { decodeFields } from './parameters'
import type { Fields } from './parameters'
import type { Change, Period } from './trends'

export const codes = ['sources', 'increasing', 'decreasing', 'stable', 'insufficient_data', 'clarify', 'no_data', 'unsupported_units', 'unsupported_correlation', 'safety', 'emergency'] as const
export interface Fact { evidence_id: string; label: string; value: string; unit: string | null; reference: string | null; source_flag: string | null; value_kind: string; comparator: string | null; canonical_metric: string | null; measurement_date: string | null; measured_at: string | null; source_type: 'report' | 'manual'; page_number: number | null; calculated_range_status: 'unknown' }
export interface Source { evidence_id: string; observation_id: string; revision: number; report_id: string | null; candidate_id: string | null; review_revision: number | null; page_number: number | null; fields: Fields }
export interface Calculation { evidence_id: 't1'; rules_version: 'trends-v1'; metric: string; unit: string; window: '7d' | '30d'; timezone: string; as_of: string; history_start: string; status: 'increasing' | 'decreasing' | 'stable' | 'insufficient_data'; reason: string; current: Period; previous: Period; change: Change | null; minimum_days: number | null; unknown_date_count: number; excluded_history_count: number; latest_reason: string; latest_value: string | null; latest_day: string | null; previous_value: string | null; previous_day: string | null; latest_change: Change | null }
export interface Answer { selection: 'latest_uploaded_report' | 'recent_metric' | 'period' | 'none'; choice: { scope: 'educational'; evidence_ids: string[]; explanation_code: typeof codes[number]; limitation: 'bounded_current_evidence_not_diagnosis'; follow_up: 'professional_context' }; facts: Fact[]; calculation: Calculation | null; sources: Source[]; text: string }
export interface Conversation { id: string; created_at: string; updated_at: string }
export interface Message { id: string; conversation_id: string; role: 'user' | 'assistant'; status: 'received' | 'generating' | 'ready' | 'failed' | 'stale'; content: string | null; answer: Answer | null; error_category: string | null; provider: 'gemini' | 'mock-test' | 'rules' | null; model: string | null; prompt_version: 'assistant-evidence-v1'; schema_version: 'assistant-closed-v1'; created_at: string }
export interface Thread { conversation: Conversation; messages: Message[]; provider_available: boolean }
export interface ConversationList { conversations: Conversation[]; provider_available: boolean }
function fail(): never { throw new Error('The conversation could not be verified.') }
function obj(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) return fail(); return v as Record<string, unknown> }
function id(v: unknown): v is string { return typeof v === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v) }
function text(v: unknown, max = 2000): v is string { return typeof v === 'string' && v.length > 0 && v.length <= max }
function nullable(v: unknown, max = 2000): v is string | null { return v === null || text(v, max) }
function integer(v: unknown, max = 500): v is number { return Number.isSafeInteger(v) && Number(v) >= 0 && Number(v) <= max }
function instant(v: unknown): v is string { return typeof v === 'string' && /T.*(?:Z|[+-]\d{2}:\d{2})$/.test(v) && Number.isFinite(Date.parse(v)) }
function day(v: unknown): v is string { return typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) && Number.isFinite(Date.parse(v)) && new Date(v).toISOString().slice(0, 10) === v }
function decimal(v: unknown): v is string { return typeof v === 'string' && /^-?\d{1,45}(?:\.\d{1,20})?$/.test(v) }
function change(v: unknown): Change | null { if (v === null) return null; const c = obj(v); if (!decimal(c.absolute) || !(c.percent === null || decimal(c.percent))) return fail(); return c as unknown as Change }
function period(v: unknown, days: number): Period { const p = obj(v); if (!day(p.start) || !day(p.end) || (Date.parse(p.end) - Date.parse(p.start)) / 86400000 !== days - 1 || !integer(p.sample_count) || !integer(p.excluded_count) || !integer(p.observed_days, days) || p.observed_days > p.sample_count || ![p.coverage_percent, p.median, p.observed_range].every(n => n === null || decimal(n)) || ![p.first_day, p.last_day].every(d => d === null || day(d))) return fail(); return p as unknown as Period }
export function decodeCalculation(value: unknown): Calculation {
  const c = obj(value)
  if (c.evidence_id !== 't1' || c.rules_version !== 'trends-v1' || !['weight', 'heart_rate', 'hemoglobin', 'tsh', 'vitamin_d_unspecified', 'glucose_unspecified', 'crp'].includes(String(c.metric)) || !text(c.unit, 60) || !['7d', '30d'].includes(String(c.window)) || !text(c.timezone, 64) || !instant(c.as_of) || !day(c.history_start) || !['increasing', 'decreasing', 'stable', 'insufficient_data'].includes(String(c.status)) || !integer(c.unknown_date_count, Number.MAX_SAFE_INTEGER) || !integer(c.excluded_history_count) || !['available', 'no_numeric_observations', 'current_coverage', 'previous_coverage', 'occasional_metric'].includes(String(c.reason)) || !['available', 'fewer_than_two_days', 'ambiguous_same_day', 'no_dated_numeric_data'].includes(String(c.latest_reason))) return fail()
  try { new Intl.DateTimeFormat('en', { timeZone: c.timezone }) } catch { return fail() }
  const days = c.window === '7d' ? 7 : 30, current = period(c.current, days), previous = period(c.previous, days), delta = change(c.change), latest = change(c.latest_change)
  if (Date.parse(current.start) - Date.parse(previous.end) !== 86400000 || c.history_start > previous.start || ![c.latest_day, c.previous_day].every(d => d === null || day(d)) || !nullable(c.latest_value, 100) || !nullable(c.previous_value, 100) || (c.status === 'insufficient_data' ? delta !== null : delta === null) || (c.latest_reason === 'available' ? (!latest || !c.latest_day || !c.previous_day || !c.latest_value || !c.previous_value) : latest !== null)) return fail()
  if (c.minimum_days !== null && c.minimum_days !== Math.ceil(days / 2)) return fail()
  return { ...c, current, previous, change: delta, latest_change: latest } as unknown as Calculation
}
export function decodeAnswer(value: unknown): Answer {
  const a = obj(value), choice = obj(a.choice)
  if (!['latest_uploaded_report', 'recent_metric', 'period', 'none'].includes(String(a.selection)) || choice.scope !== 'educational' || choice.limitation !== 'bounded_current_evidence_not_diagnosis' || choice.follow_up !== 'professional_context' || !codes.includes(choice.explanation_code as typeof codes[number]) || !Array.isArray(choice.evidence_ids) || !Array.isArray(a.facts) || a.facts.length > 20 || !Array.isArray(a.sources) || a.sources.length !== a.facts.length || !text(a.text, 1000)) return fail()
  const facts = a.facts.map((v, i) => { const f = obj(v); if (f.evidence_id !== `e${i + 1}` || !text(f.label, 160) || !text(f.value, 100) || !nullable(f.unit, 60) || !nullable(f.reference, 160) || !nullable(f.source_flag, 100) || !nullable(f.canonical_metric, 80) || !['numeric', 'qualitative', 'titre', 'interval', 'ordinal', 'unparsed'].includes(String(f.value_kind)) || ![null, '<', '>', '<=', '>=', '=', '≤', '≥'].includes(f.comparator as string | null) || f.calculated_range_status !== 'unknown' || !(f.measurement_date === null || day(f.measurement_date)) || !(f.measured_at === null || instant(f.measured_at))) return fail(); if (f.source_type === 'manual' ? (f.measured_at === null || f.measurement_date !== null || f.page_number !== null) : (f.source_type !== 'report' || f.measured_at !== null || !integer(f.page_number, 20) || f.page_number === 0)) return fail(); return f as unknown as Fact })
  const sources = a.sources.map((v, i) => { const s = obj(v), f = facts[i]!, fields = decodeFields(s.fields); if (s.evidence_id !== f.evidence_id || !id(s.observation_id) || !integer(s.revision, 100) || s.revision === 0 || !(s.report_id === null || id(s.report_id)) || !(s.candidate_id === null || id(s.candidate_id)) || !(s.review_revision === null || (integer(s.review_revision, 20) && s.review_revision > 0)) || s.page_number !== f.page_number || fields.original_label !== f.label || fields.raw_value !== f.value || fields.original_unit !== f.unit || fields.raw_reference !== f.reference || fields.source_flag !== f.source_flag || fields.canonical_metric !== f.canonical_metric || fields.value_kind !== f.value_kind || fields.comparator !== f.comparator || (f.source_type === 'report' ? (!s.report_id || !s.candidate_id || !s.review_revision) : (s.report_id !== null || s.candidate_id !== null || s.review_revision !== null))) return fail(); return { ...s, fields } as unknown as Source })
  if (new Set(sources.map(s => s.observation_id)).size !== sources.length) return fail()
  const calculation = a.calculation === null ? null : decodeCalculation(a.calculation), expected = [...facts.map(f => f.evidence_id), ...(calculation ? ['t1'] : [])]
  if (JSON.stringify(expected) !== JSON.stringify(choice.evidence_ids) || (calculation && (choice.explanation_code !== calculation.status || a.selection !== 'period')) || (facts.length > 0 && choice.explanation_code !== 'sources') || (!expected.length && ['sources', 'increasing', 'decreasing', 'stable', 'insufficient_data'].includes(String(choice.explanation_code)))) return fail()
  return { ...a, facts, sources, calculation } as unknown as Answer
}
function conversation(value: unknown): Conversation { const c = obj(value); if (!id(c.id) || !instant(c.created_at) || !instant(c.updated_at)) return fail(); return { id: c.id, created_at: c.created_at, updated_at: c.updated_at } }
export function decodeConversationList(value: unknown): ConversationList { const v = obj(value); if (!Array.isArray(v.conversations) || v.conversations.length > 20 || typeof v.provider_available !== 'boolean') return fail(); const conversations = v.conversations.map(conversation); if (new Set(conversations.map(c => c.id)).size !== conversations.length) return fail(); return { conversations, provider_available: v.provider_available } }
export function decodeThread(value: unknown): Thread {
  const v = obj(value), c = conversation(v.conversation)
  if (!Array.isArray(v.messages) || v.messages.length > 50 || typeof v.provider_available !== 'boolean') return fail()
  const messages = v.messages.map(value => { const m = obj(value); if (!id(m.id) || m.conversation_id !== c.id || !instant(m.created_at) || m.prompt_version !== 'assistant-evidence-v1' || m.schema_version !== 'assistant-closed-v1' || !['received', 'generating', 'ready', 'failed', 'stale'].includes(String(m.status)) || ![null, 'unavailable', 'invalid_output', 'timeout', 'source_changed', 'interrupted', 'rate_limit'].includes(m.error_category as string | null)) return fail(); if (m.provider === null ? m.model !== null : ({ gemini: 'gemini-3.8-flash', 'mock-test': 'deterministic-test', rules: 'rules-v1' }[String(m.provider)] !== m.model)) return fail(); const answer = m.answer === null ? null : decodeAnswer(m.answer); if (m.role === 'user' ? (!text(m.content) || m.status !== 'received' || answer !== null || m.provider !== null) : (m.role !== 'assistant' || m.content !== null || m.status === 'received' || (m.status === 'ready' ? !answer || m.provider === null : answer !== null))) return fail(); return { ...m, answer } as unknown as Message })
  if (new Set(messages.map(m => m.id)).size !== messages.length) return fail()
  return { conversation: c, messages, provider_available: v.provider_available }
}
const base = '/assistant/conversations'
function path(identifier: string) { if (!id(identifier)) return fail(); return `${base}/${identifier}` }
export const listConversations = (owner: string, signal?: AbortSignal) => accountOwnedRead(base, decodeConversationList, owner, signal)
export async function getConversation(identifier: string, owner: string, signal?: AbortSignal) { const result = await accountOwnedRead(path(identifier), decodeThread, owner, signal); if (result.conversation.id !== identifier) return fail(); return result }
export const createConversation = (key: string, owner: string, signal?: AbortSignal) => accountMutation(base, { idempotency_key: key }, decodeThread, owner, 'POST', signal)
export async function sendMessage(identifier: string, content: string, key: string, owner: string, signal?: AbortSignal) { const result = await accountMutation(`${path(identifier)}/messages`, { content, idempotency_key: key }, decodeThread, owner, 'POST', signal, 75_000); if (result.conversation.id !== identifier) return fail(); return result }
export const deleteConversation = (identifier: string, owner: string, signal?: AbortSignal) => accountMutation(path(identifier), {}, value => { if (obj(value).message !== 'Conversation deleted.') return fail() }, owner, 'DELETE', signal)
